name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Format
        run: flutter format .

      - name: Analyze
        run: flutter analyze lib

      - name: Build & Test
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CONNECT_TIMEOUT: 100000
          SEND_TIMEOUT: 1000000
          RECEIVE_TIMEOUT: 1000000
          RECEIVE_DATA_WHEN_STATUS_ERROR: true
        run: flutter build appbundle -t lib/main_staging.dart --flavor production